version: '3'
services:
  postgres:
    image: postgres:latest
    environment:
      POSTGRES_PASSWORD: postgre
      POSTGRES_USER: root
      POSTGRES_DB: simplilearn
    ports:
      - "5433:5432"
  web-app:
    build:
      context: ./client
      dockerfile: Dockerfile
    volumes:
      - /app/node_modules
      - ./client:/app
    ports:
      - '3000:3000'
    restart: on-failure
    container_name: web-app
  server:
    build:
      context: ./server
      dockerfile: Dockerfile
    ports:
      - '1337:1337'
    restart: on-failure
    container_name: server
    volumes:
      - /app/node_modules # Inside the container, don't try to override this folder, just leave as is
      - ./server:/app # Look at the server directory and copy everything into the app folder in the container
    depends_on:
      - postgres
    environment:
      DATABASE_URL: postgres://root:postgre@postgres:5432/simplilearn
